#!/usr/bin/env bash
# Regenerates ext/vendor/ from scratch using only npm-published packages.
# This is what makes the extension reproducible from source: nothing under
# ext/vendor is hand-edited, it's all a deterministic copy of two npm
# packages' published browser/WASM build artifacts.
#
# Usage: ./scripts/vendor.sh

set -euo pipefail
cd "$(dirname "$0")/.."

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "==> Installing @huggingface/transformers into a scratch dir (scripts skipped; we don't need the native onnxruntime-node build)"
(
  cd "$TMPDIR"
  npm init -y >/dev/null
  npm install @huggingface/transformers --ignore-scripts >/dev/null
)

SRC="$TMPDIR/node_modules/@huggingface/transformers/dist"
# onnxruntime-web may be hoisted to the top-level node_modules or nested
# under @huggingface/transformers/node_modules depending on what else is
# installed; resolve it robustly instead of hardcoding the path.
ORT_PKG_DIR=$(find "$TMPDIR/node_modules" -maxdepth 4 -type d -path "*onnxruntime-web" | head -1)
ORT_SRC="$ORT_PKG_DIR/dist"

mkdir -p ext/vendor/ort

echo "==> Verifying which ORT wasm filenames transformers.web.min.js actually references..."
NEEDED=$(grep -o 'ort-wasm[a-zA-Z0-9_.-]*\.\(mjs\|wasm\)' "$SRC/transformers.web.min.js" | sort -u)
echo "$NEEDED"

cp "$SRC/transformers.web.min.js" ext/vendor/transformers.web.min.js
while IFS= read -r fname; do
  [ -z "$fname" ] && continue
  cp "$ORT_SRC/$fname" "ext/vendor/ort/$fname"
done <<< "$NEEDED"

# transformers.web.min.js also contains *bare* module specifiers that
# Node/bundler tooling resolves via node_modules but a plain browser
# <script type=module> cannot resolve on its own. Worse, unlike a normal
# webpage, a Chrome extension's Manifest V3 CSP can't paper over this with
# an import map either: extension pages are barred from running ANY inline
# <script> (no 'unsafe-inline', no hash, no nonce exceptions at all), and
# `<script type="importmap">` separately forbids the `src` attribute per
# the HTML spec, so there's no external-file workaround for import maps
# either. The only CSP-compliant fix is to rewrite each bare specifier to a
# normal relative path directly inside the vendored file at build time.

# 1) "onnxruntime-web/webgpu" -> the WebGPU execution-provider bundle.
if grep -q 'from"onnxruntime-web/webgpu"' "$SRC/transformers.web.min.js"; then
  cp "$ORT_SRC/ort.webgpu.bundle.min.mjs" "ext/vendor/ort/ort.webgpu.bundle.min.mjs"
  sed -i 's#from"onnxruntime-web/webgpu"#from"./ort/ort.webgpu.bundle.min.mjs"#' ext/vendor/transformers.web.min.js
  echo "==> Patched bare specifier onnxruntime-web/webgpu -> ./ort/ort.webgpu.bundle.min.mjs"
fi

# 2) "onnxruntime-common" -> shared Tensor/type definitions package used by
# both onnxruntime-web and onnxruntime-node. It's small (~120KB) and fully
# self-contained (only relative imports between its own files), so we
# vendor the whole dist/esm/ directory verbatim and patch the one bare
# specifier that points at it.
if grep -q 'from"onnxruntime-common"' "$SRC/transformers.web.min.js"; then
  ORTC_PKG_DIR=$(find "$TMPDIR/node_modules" -maxdepth 5 -type d -path "*onnxruntime-common" | head -1)
  mkdir -p ext/vendor/onnxruntime-common
  cp "$ORTC_PKG_DIR"/dist/esm/*.js ext/vendor/onnxruntime-common/
  sed -i 's#from"onnxruntime-common"#from"./onnxruntime-common/index.js"#' ext/vendor/transformers.web.min.js
  echo "==> Patched bare specifier onnxruntime-common -> ./onnxruntime-common/index.js (vendored $(ls ext/vendor/onnxruntime-common | wc -l) files)"
fi

# Sanity check: fail loudly at build time (not silently at runtime in
# Chrome) if any bare specifier was missed.
REMAINING=$(grep -oE 'from"[a-zA-Z@][a-zA-Z0-9@/_.-]*"' ext/vendor/transformers.web.min.js | grep -v '^from"\./' | sort -u || true)
if [ -n "$REMAINING" ]; then
  echo "!! WARNING: possible unpatched bare specifier(s) remain in transformers.web.min.js:"
  echo "$REMAINING"
  echo "!! These will fail with 'Failed to resolve module specifier' in Chrome. Investigate before shipping."
fi

VERSION=$(node -p "require('$TMPDIR/node_modules/@huggingface/transformers/package.json').version")
ORT_VERSION=$(node -p "require('$ORT_PKG_DIR/package.json').version")

cat > ext/vendor/PROVENANCE.txt <<EOF
Generated by scripts/vendor.sh
@huggingface/transformers version: $VERSION
onnxruntime-web version (nested dep): $ORT_VERSION
Files copied verbatim from each package's published dist/ directory.
No files in this directory are hand-modified.
EOF

echo "==> Done. ext/vendor now contains @huggingface/transformers@$VERSION (+ onnxruntime-web@$ORT_VERSION WASM binaries)."
